- name: Generate registration command and Register the new vm using register token
  hosts: localhost
  tasks:
    - name: Generate registration command
      redhat.satellite.registration_command:
        username: "jmungin3"
        password: "{{ satellite_pass }}"
        server_url: "https://satellite2.core.gtri.org"
        activation_keys: "{{ ACTIV_KEY }}"

